### ISSUE TITLE
GUI, Connect with ports and IP adress

### ISSUE THREAD

**Issue by Danielh21** [rpuls/CA-chat#12]

**Comment by rpuls** [comment]
might be done. depends on your opinion about how its made. you now HAVE to fill in ip and port and username before clicking on login button. instead of giving the GUI as an agument i changed to give String ip , int port, and listener

THEN when pressed a client will be instanciated, and socket will be connected to the given arguments (parameters) this makes it easier to close the client, and to avoid the scanner exception. 

we can change it back if you disagree, and want to connect to the server right away when GUI is executed.

**Comment by Danielh21** [comment]
I like the way of doing that. Its more user friendly, and since the GUI i suppose to be used by none computer experts, it is easier than passing args in the command line
