### ISSUE TITLE
Refactor/Relocate Logic in Decoder

### ISSUE THREAD

**Issue by Danielh21** [rpuls/CA-chat#18]

**Comment by rpuls** [comment]
think this is not needed anyway. server logic could be a bit more clear is decoder was called "messageDecoder" since it is it's only job atm. the rest of the protocal i checked in the clientHandler which is fine for now since our protocol only consists of a few command checks. if it was a big protocal with many commands we might want to do the checks a different place. Whats your opinion on this?

**Comment by Danielh21** [comment]
I also think it is okay, that there are logic in the decoder. The only thing is whether or not the decoder should send the message back to the server directly or if it should go through the clienthandler
